### ISSUE TITLE
Undefined linker object

### ISSUE THREAD

**Issue by MaciejHadam** [mgcrea/angular-touch-nav#7]
Hi,

I cannot see how this module works.
After i've included ngTouchNav into my app I've generated an error.

TypeError: undefined is not a function
    at update (....vendor/angular-touch-nav/angular-touch-nav.js:52:19)

Browser: 29.0.1547.57
AngularJS: 1.2.0rc1

Maybe this is problem with integration this component in my project.

Any example project would be appreciated.

**Comment by gunn** [comment]
I think the project was updated to work with edge angular rather than plain 1.2.0r1
Try https://raw.github.com/mgcrea/angular-touch-nav/56d7d71da/dist/angular-touch-nav.js

Is that right @mgcrea? If so maybe there should be an edge branch

**Comment by mgcrea** [comment]
@gunn, that's right, just added an edge branch & did rollback master.
